github.com:
    users:
        baguettesabot:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: baguettesabot
