splash = false

wallpaper {
	monitor = HDMI-A-1
	path = ~/wallpapers/Cyberpunk2077_5thAnniversary_KV_Vdecal_2560x1440.png
}

wallpaper {
	monitor = DP-1
	path = ~/wallpapers/female-v-cyberpunk-3840x2160-13542.jpg

}
